//
//  CityCode.swift
//  SwiftPersianTools
//
//  Created by Saeed on 6/14/21.
//

import Foundation

struct CityCodeStruct {
    var parentId: Int
    var city: String
    var code: [Int]
}

struct CityCode {
    var cities: [CityCodeStruct]

    init() {
        self.cities = []
        self.cities.append(CityCodeStruct(parentId: 1, city: "آذرشهر", code: [169]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "اسکو", code: [170]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "اهر", code: [149, 150]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "بستان آباد", code: [171]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "بناب", code: [168]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "تبریز", code: [136, 137, 138]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "ترکمانچای", code: [545]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "جلفا", code: [505]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "چاروایماق", code: [636]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "سراب", code: [164, 165]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "شبستر", code: [172]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "صوفیان", code: [623]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "عجب شیر", code: [506]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "کلیبر", code: [519]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "مراغه", code: [154, 155]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "ورزقان", code: [567]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "هریس", code: [173]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "هشترود", code: [159, 160]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "هوراند", code: [604]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "ارومیه", code: [274, 275]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "اشنویه", code: [295]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "انزل", code: [637]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "بوکان", code: [292]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "پلدشت", code: [492]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "پیرانشهر", code: [289]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "تخت سلیمان", code: [677]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "تکاب", code: [294]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "چایپاره", code: [493]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "خوی", code: [279, 280]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "سردشت", code: [288]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "سلماس", code: [284, 285]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "سیلوانه", code: [638]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "سیه چشمه(چالدران)", code: [291]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "شوط", code: [640]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "شاهین دژ", code: [293]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "کشاورز", code: [675]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "ماکو", code: [282, 283]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "مهاباد", code: [286, 287]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "میاندوآب", code: [296, 297]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "نقده", code: [290]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "اسدآباد", code: [400, 401]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "بهار", code: [404, 405]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "تویسرکان", code: [397]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "رزن", code: [398, 399]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "شراء و پیشخوار", code: [647]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "فامنین", code: [502]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "قلقل رود", code: [584]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "کبودرآهنگ", code: [402, 403]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "ملایر", code: [392, 393]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "نهاوند", code: [395, 396]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "همدان", code: [387, 386]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "ابرکوه", code: [502]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "اردکان", code: [444]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "اشکذر", code: [551]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "بافق", code: [447]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "بهاباد", code: [561]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "تفت", code: [445]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "دستگردان", code: [718]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "طبس", code: [083]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "مهریز", code: [446]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "میبد", code: [448]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "نیر", code: [552]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "هرات و مروست", code: [543]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "یزد", code: [442, 443]))

        self.cities.append(CityCodeStruct(parentId: 5, city: "آشتیان", code: [051]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "اراک", code: [052, 053]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "تفرش", code: [058]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "خمین", code: [055]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "خنداب", code: [617]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "دلیجان", code: [057]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "زرند مرکزی", code: [618]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "ساوه", code: [059, 060]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "سربند", code: [061, 062]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "فراهان", code: [544]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "محلات", code: [056]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "وفس", code: [571]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "هندودر", code: [593]))

        self.cities.append(CityCodeStruct(parentId: 6, city: "ابوموسی", code: [667]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "بستک", code: [348]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "بشاگرد", code: [586]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "بندرعباس", code: [338, 339]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "بندرلنگه", code: [343, 344]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "جاسک", code: [346]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "حاجی آباد", code: [337]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "خمیر", code: [554]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "رودان", code: [469]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "فین", code: [537]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "قشم", code: [345]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "گاوبندی", code: [470]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "میناب", code: [341, 342]))

        self.cities.append(CityCodeStruct(parentId: 7, city: "ازنا", code: [482, 484]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "اشترینان", code: [557]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "الشتر", code: [418]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "الیگودرز", code: [416, 417]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "بروجرد", code: [412, 413]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "پاپی", code: [592]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "چغلوندی", code: [612]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "چگنی", code: [613]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "خرم آباد", code: [406, 407]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "دورود", code: [421]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "رومشکان", code: [598]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "کوهدشت", code: [419]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "ملاوی(پلدختر)", code: [385]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "نورآباد(دلفان)", code: [420]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "ویسیان", code: [528]))

        self.cities.append(CityCodeStruct(parentId: 8, city: "آمل", code: [213, 214]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بابل", code: [205, 206]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بابل", code: [498]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بندپی", code: [568]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بندپی شرقی", code: [711]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بهشهر", code: [217, 218]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "تنکابن", code: [221]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "جویبار", code: [582]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "چالوس", code: [483]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "چمستان", code: [625]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "چهاردانگه", code: [576]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "دودانگه", code: [578]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "رامسر", code: [227]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "ساری", code: [208, 209]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "سوادکوه", code: [225]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "شیرگاه", code: [577]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "عباس آباد", code: [712]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "قائمشهر", code: [215, 216]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "کجور", code: [626]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "کلاردشت", code: [627]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "گلوگاه", code: [579]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "میاندورود", code: [713]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "نکاء", code: [499]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "نور", code: [222]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "نوشهر", code: [219, 220]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "هراز و محمودآباد", code: [500, 501]))

        self.cities.append(CityCodeStruct(parentId: 9, city: "آزادشهر", code: [623]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "آق قلا", code: [497]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "بندرترکمن", code: [223]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "بندرگز", code: [689]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "رامیان", code: [487]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "علی آباد", code: [226]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "کردکوی", code: [224]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "کلاله", code: [386]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "گرگان", code: [211, 212]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "گمیشان", code: [628]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "گنبد کاووس", code: [202, 203]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "مراوه تپه", code: [531]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "مینودشت", code: [288]))

        self.cities.append(CityCodeStruct(parentId: 10, city: "آستارا", code: [261]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "آستانه", code: [273]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "املش", code: [630]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "بندرانزلی", code: [264]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "خمام", code: [518]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رحیم آباد", code: [631]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رشت", code: [258, 259]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رضوانشهر", code: [570]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رودبار", code: [265]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رودسر", code: [268, 269]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "سنگر", code: [653]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "سیاهکل", code: [517]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "شفت", code: [569]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "صومعه سرا", code: [267]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "طالش", code: [262, 263]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "عمارلو", code: [593]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "فومن", code: [266]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "کوچصفهان", code: [693]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "لاهیجان", code: [271, 272]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "لشت نشاء", code: [694]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "لنگرود", code: [270]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "ماسال و شاندرمن", code: [516]))

        self.cities.append(CityCodeStruct(parentId: 11, city: "اسلام آباد", code: [333, 334]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "باینگان", code: [691]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "پاوه", code: [323, 322]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "ثلاث باباجانی", code: [595]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "جوانرود", code: [395]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "حمیل", code: [641]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "روانسر", code: [596]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "سرپل ذهاب", code: [336]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "سنقر", code: [335]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "صحنه", code: [496]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "قصرشیرین", code: [337]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "کرمانشاه", code: [324, 325]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "کرند", code: [394]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "کنگاور", code: [330]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "گیلانغرب", code: [332]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "هرسین", code: [331]))

        self.cities.append(CityCodeStruct(parentId: 12, city: "باشت", code: [687]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "بویراحمد(یاسوج)", code: [422, 423]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "بهمنی", code: [599]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "چاروسا", code: [600]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "دروهان", code: [688]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "کهکیلویه(دهدشت)", code: [424, 425]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "گچساران(دوگنبدان)", code: [426]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "لنده", code: [550]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "مارگون", code: [697]))

        self.cities.append(CityCodeStruct(parentId: 13, city: "بانه", code: [384]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "بیجار", code: [377, 378]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "دهگلان", code: [558]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "دیواندره", code: [385]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "سروآباد", code: [646]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "سقز", code: [375, 376]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "سنندج", code: [372, 373]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "قروه", code: [379, 380]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "کامیاران", code: [383]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "کرانی", code: [674]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "مریوان", code: [381, 382]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "نمشیر", code: [676]))

        self.cities.append(CityCodeStruct(parentId: 14, city: "ارزونیه", code: [722]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "انار", code: [542]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "بافت", code: [312, 313]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "بردسیر", code: [317]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "بم", code: [310, 311]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "جیرفت", code: [302, 303]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "رابر", code: [583]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "راور", code: [321]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "راین", code: [382]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "رفسنجان", code: [304, 305]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "رودبار کهنوج", code: [536]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "ریگان", code: [605]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "زرند", code: [308, 309]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "سیرجان", code: [306, 307]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "شهداد", code: [319]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "شهربابک", code: [313, 314]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "عنبرآباد", code: [606]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "فهرج", code: [320]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "قلعه گنج", code: [698]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "کرمان", code: [298, 299]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "کوهبنان", code: [535]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "کهنوج", code: [315, 316]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "گلباف", code: [318]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "ماهان", code: [607]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "منوجان", code: [608]))

        self.cities.append(CityCodeStruct(parentId: 15, city: "آبیک", code: [508]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "آوج", code: [538]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "البرز", code: [728]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "بوئین زهرا", code: [509]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "تاکستان", code: [438, 439]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "رودبار الموت", code: [580]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "رودبار شهرستان", code: [590]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "ضیاءآباد", code: [559]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "طارم سفلی", code: [588]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "قزوین", code: [431, 432]))

        self.cities.append(CityCodeStruct(parentId: 16, city: "قم", code: [037, 038]))
        self.cities.append(CityCodeStruct(parentId: 16, city: "کهک", code: [702]))

        self.cities.append(CityCodeStruct(parentId: 17, city: "آباده", code: [240, 241]))

        self.cities.append(CityCodeStruct(parentId: 26, city: "شهرری", code: [049, 048]))
    }
}

