//
//  CityCode.swift
//  SwiftPersianTools
//
//  Created by Saeed on 6/14/21.
//

import Foundation

struct CityCodeStruct {
    var parentId: Int
    var city: String
    var code: [Int]
}

struct CityCode {
    var cities: [CityCodeStruct]

    init() {
        self.cities = []
        self.cities.append(CityCodeStruct(parentId: 1, city: "آذرشهر", code: [169]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "اسکو", code: [170]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "اهر", code: [149, 150]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "بستان آباد", code: [171]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "بناب", code: [168]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "تبریز", code: [136, 137, 138]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "ترکمانچای", code: [545]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "جلفا", code: [505]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "چاروایماق", code: [636]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "سراب", code: [164, 165]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "شبستر", code: [172]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "صوفیان", code: [623]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "عجب شیر", code: [506]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "کلیبر", code: [519]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "مراغه", code: [154, 155]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "ورزقان", code: [567]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "هریس", code: [173]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "هشترود", code: [159, 160]))
        self.cities.append(CityCodeStruct(parentId: 1, city: "هوراند", code: [604]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "ارومیه", code: [274, 275]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "اشنویه", code: [295]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "انزل", code: [637]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "بوکان", code: [292]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "پلدشت", code: [492]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "پیرانشهر", code: [289]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "تخت سلیمان", code: [677]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "تکاب", code: [294]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "چایپاره", code: [493]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "خوی", code: [279, 280]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "سردشت", code: [288]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "سلماس", code: [284, 285]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "سیلوانه", code: [638]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "سیه چشمه(چالدران)", code: [291]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "شوط", code: [640]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "شاهین دژ", code: [293]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "کشاورز", code: [675]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "ماکو", code: [282, 283]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "مهاباد", code: [286, 287]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "میاندوآب", code: [296, 297]))
        self.cities.append(CityCodeStruct(parentId: 2, city: "نقده", code: [290]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "اسدآباد", code: [400, 401]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "بهار", code: [404, 405]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "تویسرکان", code: [397]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "رزن", code: [398, 399]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "شراء و پیشخوار", code: [647]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "فامنین", code: [502]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "قلقل رود", code: [584]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "کبودرآهنگ", code: [402, 403]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "ملایر", code: [392, 393]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "نهاوند", code: [395, 396]))
        self.cities.append(CityCodeStruct(parentId: 3, city: "همدان", code: [387, 386]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "ابرکوه", code: [502]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "اردکان", code: [444]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "اشکذر", code: [551]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "بافق", code: [447]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "بهاباد", code: [561]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "تفت", code: [445]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "دستگردان", code: [718]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "طبس", code: [083]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "مهریز", code: [446]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "میبد", code: [448]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "نیر", code: [552]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "هرات و مروست", code: [543]))
        self.cities.append(CityCodeStruct(parentId: 4, city: "یزد", code: [442, 443]))

        self.cities.append(CityCodeStruct(parentId: 5, city: "آشتیان", code: [051]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "اراک", code: [052, 053]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "تفرش", code: [058]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "خمین", code: [055]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "خنداب", code: [617]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "دلیجان", code: [057]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "زرند مرکزی", code: [618]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "ساوه", code: [059, 060]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "سربند", code: [061, 062]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "فراهان", code: [544]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "محلات", code: [056]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "وفس", code: [571]))
        self.cities.append(CityCodeStruct(parentId: 5, city: "هندودر", code: [593]))

        self.cities.append(CityCodeStruct(parentId: 6, city: "ابوموسی", code: [667]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "بستک", code: [348]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "بشاگرد", code: [586]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "بندرعباس", code: [338, 339]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "بندرلنگه", code: [343, 344]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "جاسک", code: [346]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "حاجی آباد", code: [337]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "خمیر", code: [554]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "رودان", code: [469]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "فین", code: [537]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "قشم", code: [345]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "گاوبندی", code: [470]))
        self.cities.append(CityCodeStruct(parentId: 6, city: "میناب", code: [341, 342]))

        self.cities.append(CityCodeStruct(parentId: 7, city: "ازنا", code: [482, 484]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "اشترینان", code: [557]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "الشتر", code: [418]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "الیگودرز", code: [416, 417]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "بروجرد", code: [412, 413]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "پاپی", code: [592]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "چغلوندی", code: [612]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "چگنی", code: [613]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "خرم آباد", code: [406, 407]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "دورود", code: [421]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "رومشکان", code: [598]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "کوهدشت", code: [419]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "ملاوی(پلدختر)", code: [385]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "نورآباد(دلفان)", code: [420]))
        self.cities.append(CityCodeStruct(parentId: 7, city: "ویسیان", code: [528]))

        self.cities.append(CityCodeStruct(parentId: 8, city: "آمل", code: [213, 214]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بابل", code: [205, 206]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بابل", code: [498]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بندپی", code: [568]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بندپی شرقی", code: [711]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "بهشهر", code: [217, 218]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "تنکابن", code: [221]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "جویبار", code: [582]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "چالوس", code: [483]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "چمستان", code: [625]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "چهاردانگه", code: [576]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "دودانگه", code: [578]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "رامسر", code: [227]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "ساری", code: [208, 209]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "سوادکوه", code: [225]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "شیرگاه", code: [577]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "عباس آباد", code: [712]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "قائمشهر", code: [215, 216]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "کجور", code: [626]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "کلاردشت", code: [627]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "گلوگاه", code: [579]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "میاندورود", code: [713]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "نکاء", code: [499]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "نور", code: [222]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "نوشهر", code: [219, 220]))
        self.cities.append(CityCodeStruct(parentId: 8, city: "هراز و محمودآباد", code: [500, 501]))

        self.cities.append(CityCodeStruct(parentId: 9, city: "آزادشهر", code: [623]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "آق قلا", code: [497]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "بندرترکمن", code: [223]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "بندرگز", code: [689]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "رامیان", code: [487]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "علی آباد", code: [226]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "کردکوی", code: [224]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "کلاله", code: [386]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "گرگان", code: [211, 212]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "گمیشان", code: [628]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "گنبد کاووس", code: [202, 203]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "مراوه تپه", code: [531]))
        self.cities.append(CityCodeStruct(parentId: 9, city: "مینودشت", code: [288]))

        self.cities.append(CityCodeStruct(parentId: 10, city: "آستارا", code: [261]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "آستانه", code: [273]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "املش", code: [630]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "بندرانزلی", code: [264]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "خمام", code: [518]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رحیم آباد", code: [631]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رشت", code: [258, 259]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رضوانشهر", code: [570]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رودبار", code: [265]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "رودسر", code: [268, 269]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "سنگر", code: [653]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "سیاهکل", code: [517]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "شفت", code: [569]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "صومعه سرا", code: [267]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "طالش", code: [262, 263]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "عمارلو", code: [593]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "فومن", code: [266]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "کوچصفهان", code: [693]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "لاهیجان", code: [271, 272]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "لشت نشاء", code: [694]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "لنگرود", code: [270]))
        self.cities.append(CityCodeStruct(parentId: 10, city: "ماسال و شاندرمن", code: [516]))

        self.cities.append(CityCodeStruct(parentId: 11, city: "اسلام آباد", code: [333, 334]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "باینگان", code: [691]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "پاوه", code: [323, 322]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "ثلاث باباجانی", code: [595]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "جوانرود", code: [395]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "حمیل", code: [641]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "روانسر", code: [596]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "سرپل ذهاب", code: [336]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "سنقر", code: [335]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "صحنه", code: [496]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "قصرشیرین", code: [337]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "کرمانشاه", code: [324, 325]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "کرند", code: [394]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "کنگاور", code: [330]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "گیلانغرب", code: [332]))
        self.cities.append(CityCodeStruct(parentId: 11, city: "هرسین", code: [331]))

        self.cities.append(CityCodeStruct(parentId: 12, city: "باشت", code: [687]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "بویراحمد(یاسوج)", code: [422, 423]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "بهمنی", code: [599]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "چاروسا", code: [600]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "دروهان", code: [688]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "کهکیلویه(دهدشت)", code: [424, 425]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "گچساران(دوگنبدان)", code: [426]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "لنده", code: [550]))
        self.cities.append(CityCodeStruct(parentId: 12, city: "مارگون", code: [697]))

        self.cities.append(CityCodeStruct(parentId: 13, city: "بانه", code: [384]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "بیجار", code: [377, 378]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "دهگلان", code: [558]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "دیواندره", code: [385]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "سروآباد", code: [646]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "سقز", code: [375, 376]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "سنندج", code: [372, 373]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "قروه", code: [379, 380]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "کامیاران", code: [383]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "کرانی", code: [674]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "مریوان", code: [381, 382]))
        self.cities.append(CityCodeStruct(parentId: 13, city: "نمشیر", code: [676]))

        self.cities.append(CityCodeStruct(parentId: 14, city: "ارزونیه", code: [722]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "انار", code: [542]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "بافت", code: [312, 313]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "بردسیر", code: [317]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "بم", code: [310, 311]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "جیرفت", code: [302, 303]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "رابر", code: [583]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "راور", code: [321]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "راین", code: [382]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "رفسنجان", code: [304, 305]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "رودبار کهنوج", code: [536]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "ریگان", code: [605]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "زرند", code: [308, 309]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "سیرجان", code: [306, 307]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "شهداد", code: [319]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "شهربابک", code: [313, 314]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "عنبرآباد", code: [606]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "فهرج", code: [320]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "قلعه گنج", code: [698]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "کرمان", code: [298, 299]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "کوهبنان", code: [535]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "کهنوج", code: [315, 316]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "گلباف", code: [318]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "ماهان", code: [607]))
        self.cities.append(CityCodeStruct(parentId: 14, city: "منوجان", code: [608]))

        self.cities.append(CityCodeStruct(parentId: 15, city: "آبیک", code: [508]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "آوج", code: [538]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "البرز", code: [728]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "بوئین زهرا", code: [509]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "تاکستان", code: [438, 439]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "رودبار الموت", code: [580]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "رودبار شهرستان", code: [590]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "ضیاءآباد", code: [559]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "طارم سفلی", code: [588]))
        self.cities.append(CityCodeStruct(parentId: 15, city: "قزوین", code: [431, 432]))

        self.cities.append(CityCodeStruct(parentId: 16, city: "قم", code: [037, 038]))
        self.cities.append(CityCodeStruct(parentId: 16, city: "کهک", code: [702]))

        self.cities.append(CityCodeStruct(parentId: 17, city: "آباده", code: [240, 241]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "آباده طشک", code: [670]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "ارسنجان", code: [648]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "استهبان", code: [252]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "اشکنان", code: [678]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "اقلید", code: [253]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "اوز", code: [649]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "بوانات", code: [513]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "بیضا", code: [546]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "جویم", code: [671]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "جهرم", code: [246, 247]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "حاجی آباد(زرین دشت)", code: [654]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "خرامه", code: [548]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "خشت و کمارج", code: [547]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "خفر", code: [655]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "داراب", code: [248, 249]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "سپیدان", code: [253]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "سروستان", code: [514]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "سعادت آباد", code: [665]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "شیراز", code: [228, 229, 230]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "فراشبند", code: [679]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "فسا", code: [256, 257]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "فیروزآباد", code: [244, 245]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "قنقری(خرم بید)", code: [681]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "قیروکارزین", code: [723]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "کازرون", code: [236, 237]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "کوار", code: [683]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "کراش", code: [656]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "لارستان", code: [250, 251]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "لامرد", code: [515]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "مرودشت", code: [242, 243]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "ممسنی", code: [238, 239]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "مهر", code: [657]))
        self.cities.append(CityCodeStruct(parentId: 17, city: "نی ریز", code: [255]))

        self.cities.append(CityCodeStruct(parentId: 18, city: "ایوانکی", code: [684]))
        self.cities.append(CityCodeStruct(parentId: 18, city: "بسطام", code: [700]))
        self.cities.append(CityCodeStruct(parentId: 18, city: "بیارجمند", code: [642]))
        self.cities.append(CityCodeStruct(parentId: 18, city: "دامغان", code: [457]))
        self.cities.append(CityCodeStruct(parentId: 18, city: "سمنان", code: [456]))
        self.cities.append(CityCodeStruct(parentId: 18, city: "شاهرود", code: [458, 459]))
        self.cities.append(CityCodeStruct(parentId: 18, city: "گرمسار", code: [460]))
        self.cities.append(CityCodeStruct(parentId: 18, city: "مهدیشهر", code: [530]))
        self.cities.append(CityCodeStruct(parentId: 18, city: "میامی", code: [520]))

        self.cities.append(CityCodeStruct(parentId: 19, city: "ایرانشهر", code: [358, 359]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "بزمان", code: [682]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "بمپور", code: [703]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "چابهار", code: [364, 365]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "خاش", code: [371]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "دشتیاری", code: [701]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "راسک", code: [720]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "زابل", code: [366, 367]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "زابلی", code: [704]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "زاهدان", code: [361, 362]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "سراوان", code: [369, 370]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "سرباز", code: [635]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "سیب و سوران", code: [668]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "شهرکی و ناروئی(زهک)", code: [533]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "شیب آب", code: [705]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "فنوج", code: [699]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "قصرقند", code: [669]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "کنارک", code: [725]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "لاشار(اسپکه)", code: [597]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "میرجاوه", code: [611]))
        self.cities.append(CityCodeStruct(parentId: 19, city: "نیک شهر", code: [525]))

        self.cities.append(CityCodeStruct(parentId: 20, city: "آبادان", code: [181]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "آغاجاری", code: [527]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "اروندکنار", code: [585]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "امیدیه", code: [685]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "اندیکا", code: [663]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "اندیمشک", code: [192, 193]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "اهواز", code: [174, 175]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "ایذه", code: [183, 184]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "باغ ملک", code: [481]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "بندر امام خمینی", code: [706]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "بندرماهشهر", code: [194, 195]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "بهبهان", code: [185, 186]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "خرمشهر", code: [182]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "دزفول", code: [199, 200]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "دشت آزادگان", code: [198]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "رامشیر", code: [662]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "رامهرمز", code: [190, 191]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "سردشت", code: [692]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "شادگان", code: [189]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "شاوور", code: [707]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "شوش", code: [526]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "شوشتر", code: [187, 188]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "گتوند", code: [729]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "لالی", code: [730]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "مسجدسلیمان", code: [196, 197]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "هندیجان", code: [661]))
        self.cities.append(CityCodeStruct(parentId: 20, city: "هویزه", code: [680]))

        self.cities.append(CityCodeStruct(parentId: 21, city: "احمدآباد", code: [643]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "بجستان", code: [562]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "بردسکن", code: [672]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "تایباد", code: [074]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "تخت جلگه", code: [644]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "تربت جام", code: [072, 073]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "تربت حیدریه", code: [069, 070]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "جغتای", code: [521]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "جوین", code: [573]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "چناران", code: [522]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "خلیل آباد", code: [724]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "خواف", code: [076]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "درگز", code: [077]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "رشتخوار", code: [650]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "زبرخان", code: [574]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "سبزوار", code: [078, 079]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "سرخس", code: [081]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "فریمان", code: [084]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "فیض آباد", code: [651]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "قوچان", code: [086, 087]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "کاشمر", code: [089, 090]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "کلات", code: [553]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "گناباد", code: [091]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "مشهد", code: [092, 093, 094]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "مشهد منطقه2", code: [097]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "مشهد منطقه3", code: [098]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "مشهد منطقه1", code: [096]))
        self.cities.append(CityCodeStruct(parentId: 21, city: "نیشابور", code: [105, 106]))

        self.cities.append(CityCodeStruct(parentId: 22, city: "اسفراین", code: [063]))
        self.cities.append(CityCodeStruct(parentId: 22, city: "بجنورد", code: [067, 068]))
        self.cities.append(CityCodeStruct(parentId: 22, city: "جاجرم", code: [075]))
        self.cities.append(CityCodeStruct(parentId: 22, city: "رازوجرکلان", code: [591]))
        self.cities.append(CityCodeStruct(parentId: 22, city: "شیروان", code: [082]))
        self.cities.append(CityCodeStruct(parentId: 22, city: "فاروج", code: [635]))
        self.cities.append(CityCodeStruct(parentId: 22, city: "مانه و سملقان", code: [524]))

        self.cities.append(CityCodeStruct(parentId: 23, city: "اردل", code: [468]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "بروجن", code: [465]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "شهرکرد", code: [461, 462]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "فارسان", code: [467]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "فلارد", code: [632]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "کوهرنگ", code: [555]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "کیار", code: [633]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "گندمان", code: [629]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "لردگان", code: [466]))
        self.cities.append(CityCodeStruct(parentId: 23, city: "میانکوه", code: [696]))

        self.cities.append(CityCodeStruct(parentId: 24, city: "بشرویه", code: [721]))
        self.cities.append(CityCodeStruct(parentId: 24, city: "بیرجند", code: [064, 065]))
        self.cities.append(CityCodeStruct(parentId: 24, city: "درمیان", code: [523]))
        self.cities.append(CityCodeStruct(parentId: 24, city: "زیرکوه", code: [652]))
        self.cities.append(CityCodeStruct(parentId: 24, city: "سرایان", code: [719]))
        self.cities.append(CityCodeStruct(parentId: 24, city: "سربیشه", code: [716]))
        self.cities.append(CityCodeStruct(parentId: 24, city: "فردوس", code: [085]))
        self.cities.append(CityCodeStruct(parentId: 24, city: "قائنات", code: [088]))
        self.cities.append(CityCodeStruct(parentId: 24, city: "نهبندان", code: [563]))

        self.cities.append(CityCodeStruct(parentId: 25, city: "بندر دیلم", code: [529]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "بندر گناوه", code: [353]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "بوشهر", code: [349, 350]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "جم", code: [609]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "دشتستان", code: [351, 352]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "دشتی", code: [354]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "دلوار", code: [732]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "دیر", code: [357]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "سعد آباد", code: [532]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "شبانکاره", code: [610]))
        self.cities.append(CityCodeStruct(parentId: 25, city: "کنگان", code: [356]))

        self.cities.append(CityCodeStruct(parentId: 26, city: "اسلامشهر", code: [556]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "پاکدشت", code: [658]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "تهران مرکزی", code: [001, 002, 003, 004, 005, 006, 007, 008]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "تهران جنوب", code: [011]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "تهران شرق", code: [020]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "تهرانشمال", code: [025]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "تهران غرب", code: [015]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "دماوند", code: [043]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "رباط کریم", code: [666]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "ساوجبلاغ", code: [489]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "شمیران", code: [044, 045]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "شهرری", code: [049, 048]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "شهریار", code: [490, 491]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "طالقان", code: [695]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "فیروزکوه", code: [659]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "کرج", code: [031, 032]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "کهریزک", code: [664]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "نظرآباد", code: [717]))
        self.cities.append(CityCodeStruct(parentId: 26, city: "ورامین", code: [041, 042]))

        self.cities.append(CityCodeStruct(parentId: 27, city: "امور خارجه", code: [471, 472]))

        self.cities.append(CityCodeStruct(parentId: 28, city: "آبدانان", code: [454]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "ارکوازی(ملکشاهی)", code: [581]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "ایلام", code: [449, 450]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "ایوان", code: [616]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "بدره", code: [534]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "دره شهر", code: [455]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "دهلران", code: [451]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "زرین آباد", code: [726]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "شیروان لومار", code: [634]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "شیروان و چرداول", code: [453]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "موسیان", code: [727]))
        self.cities.append(CityCodeStruct(parentId: 28, city: "مهران", code: [452]))

        self.cities.append(CityCodeStruct(parentId: 29, city: "اردبیل", code: [145, 146]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "ارشق", code: [731]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "انگوت", code: [690]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "بیله سوار", code: [601]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "پارس آباد", code: [504]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "خلخال", code: [163]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "خورش رستم", code: [714]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "سرعین", code: [715]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "سنجبد(کوثر)", code: [566]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "مشکین شهر", code: [166, 167]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "مغان", code: [161, 162]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "نمین", code: [686]))
        self.cities.append(CityCodeStruct(parentId: 29, city: "نیر", code: [603]))

        self.cities.append(CityCodeStruct(parentId: 30, city: "آران و بیدگل", code: [619]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "اردستان", code: [118]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "اصفهان", code: [127, 128, 129]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "باغ بهادران", code: [620]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "بوئین و میاندشت", code: [621]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "تیران و کرون", code: [549]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "جرقویه", code: [564]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "چادگان", code: [575]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "خمینی شهر", code: [113, 114]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "خوانسار", code: [122]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "خور و بیابانک", code: [540]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "دولت آباد", code: [660]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "سمیرم", code: [120]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "سمیرم سفلی (دهاقان)", code: [512]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "شاهین شهر", code: [510, 511]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "شهرضا", code: [119]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "فریدن", code: [115]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "فریدونشهر", code: [112]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "فلاورجان", code: [110, 111]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "کاشان", code: [125, 126]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "کوهپایه", code: [565]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "گلپایگان", code: [121]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "لنجان(زرینشهر)", code: [116, 117]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "مبارکه", code: [541]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "میمه", code: [622]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "نائین", code: [124]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "نجف آباد", code: [108, 109]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "نطنز", code: [123]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "زنجان", code: [428, 427]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "ملکان", code: [507]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "مرند", code: [158]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "ابهر", code: [615]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "خرمدره", code: [615]))
        self.cities.append(CityCodeStruct(parentId: 30, city: "میانه", code: [152, 153]))

    }
}

